name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: 1.13-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cdesch/elixir-base:$IMAGE_VERSION --build-arg IMAGE_VERSION=$IMAGE_VERSION 
